[tool.poetry]
name = "detection-of-personal-data"
version = "0.1.0"
description = ""
authors = ["NourKired <n.kired@okp4.com>"]

[tool.poetry.dependencies]
python = "^3.10"
common_regex = "^1.0.2"
nltk = "^3.7"
pandas = "^1.4.2"
tqdm = "^4.64.0"
transformers = "^4.19.2"
torch = "^1.11.0"
numpy = "^1.22.4"
flake8 = "^4.0.1"
black = "^22.3.0"

[tool.poetry.dev-dependencies]
[tool.poetry.scripts]
detection-of-personal-data = "pii_detect.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
