[tool.poetry]
name = "peronnel_data_detection"
version = "0.1.0"
description = ""
authors = ["NourKired <n.kired@okp4.com>"]

[tool.poetry.dependencies]
python = "^3.9"
nltk = "^3.7"
common_regex = "^1.0.2"
pandas = "^1.4.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-bugbear = "^21.11.29"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
