
[tool.poetry]
name = "porun python3 src/main.py"
version = "0.1.0"
description = ""
authors = ["Nour Kired"]

[tool.poetry.dependencies]
python = "3.9"
click = "^8.1.3"
transformers = "^4.18.0"
pandas = "^1.4.2"
nltk = "^3.7"
common_regex = "^1.0.2"
sklearn = "^0.0"
sentencepiece = "^0.1.96"
flake8 = "^4.0.1"
openpyxl = "^3.0.9"
torch = "^1.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
