name: Publish

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  publish-docker-images:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: 1.3.1

      - name: Login to Docker registry
        run: |
          echo ${{ secrets.DOCKER_REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_REGISTRY_ID }} --password-stdin

      - name: Set up target version
        id: project_context
        run: |
          version=`poetry version -s --no-ansi -n`
          echo "version=${version}"  >> $GITHUB_OUTPUT
          echo "major=$(echo $version | cut -d. -f1)"  >> $GITHUB_OUTPUT
          echo "minor=$(echo $version | cut -d. -f2)"  >> $GITHUB_OUTPUT
          echo "revision=$(echo $version | cut -d. -f3)"  >> $GITHUB_OUTPUT
          echo "image=${GITHUB_REPOSITORY}"  >> $GITHUB_OUTPUT

      - name: Build and publish image(s)
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "Publish docker image for branch"
            docker build \
              -t ghcr.io/${{ steps.project_context.outputs.image }}:${{ steps.project_context.outputs.major }} \
              -t ghcr.io/${{ steps.project_context.outputs.image }}:${{ steps.project_context.outputs.major }}.${{ steps.project_context.outputs.minor }} \
              -t ghcr.io/${{ steps.project_context.outputs.image }}:${{ steps.project_context.outputs.version }} \
              -t ghcr.io/${{ steps.project_context.outputs.image }}:latest \
              .
          else
            echo "Publish docker image for nightly"
            docker build \
              -t ghcr.io/${{ steps.project_context.outputs.image }}:nightly \
              .
          fi
          docker push ghcr.io/${{ steps.project_context.outputs.image }} --all-tags
