name: Test

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-python-poetry:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: 1.3.1

      - name: Install project dependencies
        run: |
          poetry install

      - name: Run unit tests
        run: |
          poetry run pytest -v
